amadeus/urls.py
""" 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
"""

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from rest_framework.documentation import include_docs_urls

from .views import index


urlpatterns = [
    url(r'^users/', include('users.urls', namespace = 'users')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name = 'home'),
    url(r'^api/', include('api.urls', namespace = 'api')),
    url(r'^categories/', include('categories.urls', namespace = 'categories')),
    url(r'^subjects/', include('subjects.urls', namespace = 'subjects')),
    url(r'^groups/', include('students_group.urls', namespace = 'groups')),
    url(r'^topics/', include('topics.urls', namespace = 'topics')),
    url(r'^chat/', include('chat.urls', namespace = 'chat')),
    url(r'^mural/', include('mural.urls', namespace = 'mural')),
    url(r'^webpages/', include('webpage.urls', namespace = 'webpages')),
    url(r'^ytvideo/', include('youtube_video.urls', namespace = 'youtube')),
    url(r'^file_links/', include('file_link.urls', namespace = 'file_links')),
    url(r'^goals/', include('goals.urls', namespace = 'goals')),
    url(r'^mailsender/', include('mailsender.urls', namespace = 'mailsender')),
    url(r'^security/', include('security.urls', namespace = 'security')),
    url(r'^themes/', include('themes.urls', namespace = 'themes')),
    url(r'^pendencies/', include('notifications.urls', namespace = 'notifications')),
    url(r'^links/', include('links.urls', namespace='links')),
    url(r'^pdf_files/', include('pdf_file.urls', namespace='pdf_files')),
    url(r'^webconferences/', include('webconference.urls', namespace = 'webconferences')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^analytics/', include('analytics.urls', namespace='analytics')),
    url(r'^dashboards/', include('dashboards.urls', namespace='dashboards')),
    url(r'^bulletin/', include('bulletin.urls', namespace='bulletin')),
    url(r'^api-docs/', include_docs_urls(title = 'REST Api Documentation')),
    #API
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    #S3Direct
    url(r'^s3direct/', include('s3direct.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'session_security/', include('session_security.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

api/urls.py
""" 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
"""

from django.conf.urls import url, include

# ========== API IMPORTS ============= #
from rest_framework import routers

from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer

from users.views import UserViewSet
from log.views import LogViewSet
from . import views

schema_view = get_schema_view(title = 'REST API', renderer_classes = [OpenAPIRenderer, SwaggerUIRenderer])

router = routers.DefaultRouter()

router.register(r'logs', LogViewSet)
router.register(r'usersapi', UserViewSet)
router.register(r'users', views.LoginViewset)
router.register(r'subjects', views.SubjectViewset)
router.register(r'participants', views.ParticipantsViewset)
router.register(r'chat', views.ChatViewset)

urlpatterns = [
	#API REST
    url(r'^', include(router.urls)),
    url(r'^token$', views.getToken),
    url(r'^docs/', schema_view, name="docs"),
]

themes/urls.py
""" 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
"""

from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name = 'manage'),
	url(r'^basic_elements$', views.BasicElementsSettings.as_view(), name = 'basic'),
	url(r'^css_selector$', views.CSSStyleSettings.as_view(), name = 'css'),
	url(r'^contrast$',views.Contrast, name = 'contrast'),
]

users/urls.py
""" 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, {'next_page': 'users:login'}, name='logout'),
	url(r'^signup/$', views.RegisterUser.as_view(), name = 'signup'),
	url(r'^forgot_password/$', views.ForgotPassword.as_view(), name = 'forgot_pass'),
	url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.PasswordResetConfirmView.as_view(), name = 'reset_password_confirm'), 
	url(r'^$', views.UsersListView.as_view(), name = 'manage'),
	url(r'^create/$', views.CreateView.as_view(), name = 'create'),
	url(r'^edit/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', views.UpdateView.as_view(), name = 'update'),
	url(r'^delete/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', views.DeleteView.as_view(), name = 'delete'),
	url(r'^search/$', views.SearchView.as_view(), name = 'search'),
	url(r'^profile/$', views.Profile.as_view(), name = 'profile'),
	url(r'^edit_profile/$', views.UpdateProfile.as_view(), name = 'edit_profile'),
	url(r'^change_pass/$', views.ChangePassView.as_view(), name='change_pass'),
	url(r'^remove_account/$', views.DeleteView.as_view(), name='remove_acc'),

	
]

users/models.py
""" 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
"""

import re

from os import path
from django.db import models
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.contrib.staticfiles.templatetags.staticfiles import static

from log.models import Log

def validate_img_extension(value):
	valid_formats = ['image/jpeg','image/x-citrix-jpeg','image/png','image/x-citrix-png','image/x-png']
	
	if hasattr(value.file, 'content_type'):
		if not value.file.content_type in valid_formats:
			raise ValidationError(_('File not supported.'))

class User(AbstractBaseUser, PermissionsMixin):

	email = models.EmailField(_('Mail'), unique = True, validators = [
			validators.RegexValidator(
				re.compile('^[\w.@+-]+$'),
				_('Type a valid email. This fields should only contain letters, numbers and the characteres: @/./+/-/_ .')
				, 'invalid'
			)
		], help_text = _('Your email address that will be used to access the platform'))
	username = models.CharField(_('Name'), max_length = 100)
	last_name = models.CharField(_('Last Name'), max_length = 100)
	social_name = models.CharField(_('Social Name'), max_length = 100, blank = True, null = True)
	description = models.TextField(_('Description'), blank = True)
	image = models.ImageField(verbose_name = _('Photo'), null=True, blank = True, upload_to = 'users/', validators = [validate_img_extension])
	date_created = models.DateTimeField(_('Create Date'), auto_now_add = True)
	last_update = models.DateTimeField(_('Last Update'), auto_now = True)
	show_email = models.IntegerField(_('Show email?'), null = True, blank = True, choices = ((1, _('Allow everyone to see my address')), (2, _('Only classmates can see my address')), (3, _('Nobody can see my address'))), default = 1)
	is_staff = models.BooleanField(_('Administrator'), default = False)
	is_active = models.BooleanField(_('Active'), default = True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username', 'last_name']

	objects = UserManager()

	class Meta:
		verbose_name = _('User')
		verbose_name_plural = _('Users')

	def __str__(self):
		return self.social_name or (self.username + " " + self.last_name)

	def get_short_name(self):
		return str(self)

	@property
	def image_url(self):
		if self.image and hasattr(self.image, 'url'):
			if path.exists(self.image.path):
				return self.image.url
		
		return static('img/no_image.jpg')

	def get_items(self):
		data = Log.objects.filter(user_id = self.id)

		return data

	def is_admin(self):
		if self.is_staff:
			return _('Yes')

		return _('Is not an admin')

users/templates/users/delete.html
<!-- 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
-->

{% load static i18n permission_tags %}

<!-- Modal (remember to change the ids!!!) -->
<div class="modal fade" id="users" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
           <!-- Modal Body -->
      <div class="modal-body">
        <!-- Put ONLY your content here!!!  -->
        <form id="delete_form" action="{% url 'users:delete' email %}" method="post">
          {% csrf_token %}
          <p>{% trans 'Are you sure you want delete the user' %}: {{ acc }}?</p>
        </form>
      </div>
      <!-- Modal Footer -->
      <div id="delete-category-footer"class="modal-footer">
        <!-- Don't remove that!!!  -->
        <button type="button" class="btn btn-default btn-raised" data-dismiss="modal">{% trans "Close" %}</button>
        <button type="submit" form="delete_form" class="btn btn-success btn-raised erase-button">{% trans "Delete" %}</button>
      </div>
    </div>
  </div>
</div>

users/templates/users/list.html
<!-- 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
-->

{% extends 'base.html' %}

{% load i18n pagination django_bootstrap_breadcrumbs permission_tags static  %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Manage Users' 'users:manage' %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p>{{ message }}</p>
            </div>
        {% endfor %}
    {% endif %}

    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'users:search' %}" method="GET" class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-11 col-sm-10 col-xs-10">
                        <input type="text" class="form-control" name="search" placeholder="{% trans 'Search...' %}" />
                    </div>
                    <div class="col-md-1 col-sm-2 col-xs-2">
                        <button type="submit" class="btn btn-fab btn-fab-mini">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <a href="{% url 'users:create' %}" class="pull-right btn btn-success btn-raised btn-md"><i class="fa fa-plus"></i> {% trans 'Create User' %}</a>
        </div>
    </div>

    {% if users %}
        {% for acc in users %}
            <div class="row-fluid panel panel-default">
                <div class="panel-body">
                    <div class="col-md-3">
                        <span class="thumbnail">
                            <img src="{{ acc.image_url }}" class="img-responsive" />
                        </span>
                    </div>
                    <div class="col-md-6">
                        <p><b>{% trans 'Name' %}:</b> {{ acc }}</p>
                        <p><b>{% trans 'Email' %}:</b> {{ acc.email }}</p>
                        <p><b>{% trans 'Description' %}:</b>
                            {% autoescape off %}
                                {{ acc.description|default:_("Not Informed")|striptags|truncatechars:300 }}
                            {% endautoescape %}
                        </p>
                    </div>
                    <div class="col-md-3">
                        <div align="right">
                            <a href="{% url 'users:update' acc.email %}" class="btn btn-success btn-raised btn-sm"><i class="fa fa-edit"></i> {% trans 'Edit' %}</a>
                            <a href="javascript:delete_subject.get('{% url 'users:delete' acc.email %}','#users','#modal_remove')" class="btn btn-default btn-raised btn-sm"><i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% pagination request paginator page_obj %}
    {% else %}
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <p>{% trans 'No users found' %}</p>
            </div>
        </div>
    {% endif %}
    <div id="modal_remove">

    </div>


<script src="{% static 'js/crop.js' %}"></script> <!-- Js for cropper-->
{% endblock %}

users/templates/users/login.html
<!-- 
Copyright 2016, 2017 UFPE - Universidade Federal de Pernambuco
 
Este arquivo é parte do programa Amadeus Sistema de Gestão de Aprendizagem, ou simplesmente Amadeus LMS
 
O Amadeus LMS é um software livre; você pode redistribui-lo e/ou modifica-lo dentro dos termos da Licença Pública Geral GNU como publicada pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 
Este programa é distribuído na esperança que possa ser útil, mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU para maiores detalhes.
 
Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título "LICENSE", junto com este programa, se não, escreva para a Fundação do Software Livre (FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA.
-->

{% extends 'base.html' %}

{% load static i18n %}
{% load widget_tweaks %}

{% block nav %}
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block sidebar %}
{% endblock sidebar %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            {% if contrast_cookie %}
                <img src="{{ theme.high_contrast_logo_url }}" class="img-responsive center-block logo-login " alt="logo amadeus" />
            {% else %}
                <img src="{{ theme.large_logo_url }}" class="img-responsive center-block logo-login " alt="logo amadeus" />
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-lg-offset-2 col-md-offset-2 col-lg-8 col-md-8 col-sm-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="card">
                <div class="card-block">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <h2 class="outside-title"><strong> {% trans 'Sign in with your account' %} </strong></h2>
                        </div>
                    </div>

                    <form id="form-login" method="post" action="">
                        {% csrf_token %}
                        <div class="col-lg-10 col-md-10 col-sm-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                            <div class="form-group">
                                <input form="form-login" for="inputSmall" type="text" name="email" class="form-control" placeholder="{% trans 'Email' %}" id="inputEmail" value="{% if username %}{{username}}{% endif %}">
                            </div>
                        </div>
                        <div class="col-lg-10 col-md-10 col-sm-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                            <div class="form-group">
                                <input form="form-login" for="inputSmall" type="password" name="password" class="form-control" id="inputPassword" placeholder="{% trans 'Password' %}">
                            </div>
                        </div>

                    </form>


                    <div class="row">
                        <div class="col-lg-10 col-md-10 col-sm-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                            {% if not deny_register %}
                                <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6 text-center">
                                    <button type="submit" class="btn btn-success btn-raised btn-block" form="form-login" style="position: initial;"> {% trans 'Log in' %} </button>
                                </div>
                                <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6 text-center">
                                    <a class="btn btn-default btn-raised btn-block" href="{% url 'users:signup' %}" formaction="#" style="position: initial;">{% trans 'Sign Up' %}</a>
                                </div>
                            {% else %}
                                <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6 col-lg-offset-3 col-md-offset-3 col-sm-offset-3 col-xs-offset-3 text-center">
                                    <button type="submit" class="btn btn-success btn-raised btn-block" form="form-login" style="position: initial;"> {% trans 'Log in' %} </button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row login_subcommands hidden-sm hidden-xs">
                        {% if not deny_register %}
                            <div class="col-sm-offset-1 col-md-10 col-lg-10 col-sm-10 col-xs-12">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-right forgotPassword">
                                    <a class="pull-right" href="{% url 'users:forgot_pass' %}">{% trans 'Forgot your password?' %}</a>
                                    <li class="dropdown language-selector pull-right " style="margin-top:1px;margin-right:10px;">
                                        {% get_current_language as LANGUAGE_CODE %}

                                        <a href="#" class="dropdown-toggle hidden-sm hidden-xs" data-toggle="dropdown" data-close-others="true">
                                            <span >[{{LANGUAGE_CODE}}]  </span>
                                        </a>
                                        <a href="{% url 'themes:contrast' %}" id = "contrast_button" style="margin-left:10px;"><i class="glyphicon glyphicon-adjust hidden-sm hidden-xs"></i></a>
                                        <ul class="dropdown-menu">
                                            {% get_available_languages as LANGUAGES %}
                                            {% get_language_info_list for LANGUAGES as languages %}

                                            {% for language in languages %}
                                                <li {% if language.code == LANGUAGE_CODE %}
                                                    class="active"
                                                {% endif %}>
                                                    <a class="language-item" value-lang="{{language.code}}">
                                                        <span>{{language.code}}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                </div>
                            </div>
                        {% else %}
                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center forgotPassword">
                                    <a href="{% url 'users:forgot_pass' %}">{% trans 'Forgot your password?' %}</a>

                                    <li class="dropdown language-selector pull-right " style="margin-top:1px;margin-right:10px;">
                                        {% get_current_language as LANGUAGE_CODE %}
                                        <a href="#" class="dropdown-toggle hidden-sm hidden-xs" data-toggle="dropdown" data-close-others="true">

                                          <span>[{{LANGUAGE_CODE}}]  </span>

                                        </a>
                                        <a href="{% url 'themes:contrast'%}" style="margin-left:10px;"><i class="glyphicon glyphicon-adjust hidden-sm hidden-xs"></i></a>
                                        <ul class="dropdown-menu">
                                            {% get_available_languages as LANGUAGES %}
                                            {% get_language_info_list for LANGUAGES as languages %}
                                            {% for language in languages %}

                                                <li {% if language.code == LANGUAGE_CODE %}
                                                    class="active"
                                                {% endif %}>
                                                    <a class="language-item" value-lang="{{language.code}}">
                                                        <span>{{language.code}}</span>
                                                    </a>
                                                </li>

                                            {% endfor %}
                                        </ul>
                                    </li>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="row login_subcommands hidden-lg hidden-md">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center forgotPassword">
                                    <a href="{% url 'users:forgot_pass' %}">{% trans 'Forgot your password?' %}</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row login_subcommands hidden-lg hidden-md">
                <div class="col-sm-12 col-xs-12">
                    <div class="language-selector ">
                        <div class="btn-group dropup">
                            {% get_current_language as LANGUAGE_CODE %}

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span >[{{LANGUAGE_CODE}}]  </span>
                            </a>
                            <ul class="dropdown-menu">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}

                                {% for language in languages %}
                                    <li {% if language.code == LANGUAGE_CODE %}
                                        class="active"
                                    {% endif %}>
                                        <a class="language-item" value-lang="{{language.code}}">
                                            <span>{{language.code}}</span>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <a href="{% url 'themes:contrast' %}" id = "contrast_button_mobile" style="margin-left:10px;"><i class="glyphicon glyphicon-adjust"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script type="text/javascript">
    $("#contrast_button" ).click(function() {
      if (Cookies.get('contrast_check')) {
        Cookies.remove('contrast_check')
        //location.reload()
      }
      else {
        Cookies.set('contrast_check','contrast')
        //location.reload()
      }

    });
</script>

<script type="text/javascript">
    $("#contrast_button_mobile" ).click(function() {
      if (Cookies.get('contrast_check')) {
        Cookies.remove('contrast_check')
        //location.reload()
      }
      else {
        Cookies.set('contrast_check','contrast')
        //location.reload()
      }

    });
</script>

{% endblock%}

{% block footer %}
    {% if theme.footer_note != '' and theme.footer_note != '<p><br></p>' %}
        <div class="footer">
            <div class="row">
                <div class="col-md-12 text-center">
                    {% autoescape off %}
                        {{ theme.footer_note }}
                    {% endautoescape %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block bottommenu %}
{% endblock %}